### ISSUE TITLE
impossible de changer le subnet et l'IPv4 lan

### ISSUE THREAD

**Issue by kgersen** [LaFibre-info/Freepro#1]
Par défaut la FBPro est en `192.168.10.254` et ce n'est pas modifiable et par conséquence la plage DHCP non plus.

**Comment by phastier** [comment]
Inadmissible pour une offre "Pro" en 2021.

**Comment by PofMagicfingers** [comment]
( Je veux bien être compréhensif avec les devs qui doivent bosser dur pour corriger tous les couacs du lancement, mais ça commence à faire long quand même... Il aurait peut être été plus sage de faire plein de petites mises à jour avec des petits fixs plutot que de nous faire attendre 2 mois avec des boxs "pas finies" )
