### ISSUE TITLE
Configuration Wifi par défaut non optimum

### ISSUE THREAD

**Issue by kgersen** [LaFibre-info/Freepro#12]
largeur de bande en 5ghz qu'a 20Mhz par défaut.

![image](https://user-images.githubusercontent.com/1764578/116612906-5c7eab00-a938-11eb-996a-86a4fc6f8123.png)

**Comment by mgerini** [comment]
La configuration Wifi par défaut a été optimisée.
Wifi 2.4GHz Largeur de Bande 40Mhz
Wifi 5GHz (High et Low) Largeur de Bande 80Mhz
Cette nouvelle configuration permet de bien meilleurs résultats sur la majorité des installations

**Comment by mgerini** [comment]
> largeur de bande en 5ghz qu'a 20Mhz par défaut.
La configuration Wifi par défaut a été optimisée.
Wifi 2.4GHz Largeur de Bande 40Mhz
Wifi 5GHz (High et Low) Largeur de Bande 80Mhz
Cette nouvelle configuration permet de bien meilleurs résultats sur la majorité des installations

**Comment by kgersen** [comment]
40 Mhz par défaut en 2.4Ghz ce n'est pas un peu 'pas cool pour les voisins' pour des locaux en ville ?

**Comment by HectordeMars** [comment]
petite amélioration à faire sur l'interface client ? un scanner réseau avec les canaux de l'entourage
