### ISSUE TITLE
pas de serveur de mires pour tester le débit LAN

### ISSUE THREAD

**Issue by kgersen** [LaFibre-info/Freepro#13]
pas de serveur de mires pour tester son débit LAN (comme http://mafreebox.freebox.fr/gen/10G sur la Delta)

**Comment by rmanus** [comment]
Disponible prochainement...

**Comment by mgerini** [comment]
@kgersen Disponible dans le nouveau firmware publié ce jour : 

http://mafreebox.freepro.com/fixed/10G

**Comment by kgersen** [comment]
404. quel est l'url qui marche ? et cf #48

**Comment by kgersen** [comment]
a noter: 
`mafreebox.freepro.com  --> 212.27.38.253`
mais le reverse: 
`212.27.38.253 --> freeplayer.freebox.fr.``

je n'ouvre pas une issue pour ca mais je suis tenté.

**Comment by mgerini** [comment]
> 1. quel est l'url qui marche ? et cf [pas de notes de mise a jour pour la 1.6.2 #48](https://github.com/LaFibre-info/Freepro/issues/48)

Désolé erreur de ma part, le /fixed/ est un appel interne, le bon URL public est bien :  http://mafreebox.freepro.com/gen/10G

**Comment by kgersen** [comment]
> Désolé erreur de ma part, le /fixed/ est un appel interne, le bon URL public est bien : http://mafreebox.freepro.com/gen/10G

reponse 302.

```
curl  http://mafreebox.freepro.com/gen/10G
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

**Comment by kgersen** [comment]
correction: c'est bon manquait le -L du curl ;)

**Comment by kgersen** [comment]
par contre pas d'IPv6 ...meme sur la link-local, le port 80 est fermé

du coup il faut utiliser directement la redirection `http://<ip_link_local%int>:8095/fixed/10G` qui elle est ouverte en IPv6...

et idéalement il faudrait un unicast IPv6 aussi.

**Comment by mgerini** [comment]
@kgersen , la mire est aussi configurée pour fonctionner en v6

`
$ dig +short  AAAA mafreebox.freepro.com
fd0f:ee:b0::1
`

Et la loopback fd0f:ee:b0::1 écoute bien sur le port 80

**Comment by kgersen** [comment]
ah effectivement ca marche. bizarrement le débit en IPv6 est limité a 6.4 Gbps environ contrairement a IPv4 qui monte au max du port 10G (sur plusieurs flux toutefois).

**Comment by kgersen** [comment]
a noter que l'utilisation d'une ULA pour l'unicast IPv6 fait que par défaut IPv4 est prioritaire sur tous les OS respectant la rfc6724 ( https://datatracker.ietf.org/doc/html/rfc6724#section-10.3 )

il faut donc 'forcer' IPv6 (-6 avec curl par exemple).
