### ISSUE TITLE
Aucune documentation ou information de paramétrage des clients VPN.

### ISSUE THREAD

**Issue by kgersen** [LaFibre-info/Freepro#19]
rien en ligne.

a priori c'est du **IPSec IKEv2 EAP**

**Comment by rmanus** [comment]
La documentation sur le VPN est ici : https://support-pro.free.fr/faqs/utiliser-mon-vpn/

**Comment by kgersen** [comment]
ok mais dommage qu'on est pas lien vers cela depuis la partie VPN de l'interface d'admin.

**Comment by rmanus** [comment]
> ok mais dommage qu'on est pas lien vers cela depuis la partie VPN de l'interface d'admin.

je fais remonter le point!
