### ISSUE TITLE
3179 injoignable - impossiblité d'avoir le RIO

### ISSUE THREAD

**Issue by vivienfr** [LaFibre-info/Freepro#25]
Le 3179 est le numéro pour connaître son code RIO, permettant de garder son numéro de téléphone en cas de résiliation.

Ce numéro est injoignable actuellement pour les clients Free Pro selon sf!

**Comment by spencefoxtrot** [comment]
Pour appuyer avec le retour de "Vivien" : https://www.arcep.fr/uploads/tx_gsavis/13-0830.pdf
`L’Autorité note toutefois que, lors des travaux préparatoires à la mise en place du RIO fixe, les opérateurs
fixes proposant des offres de type « petit professionnel » dont les caractéristiques sont proches des
abonnements grand public (fourniture d’une box ainsi que quelques numéros fixes) se sont engagés à utiliser
le RIO fixe pour traiter les demandes de conservations du numéro fixe sur ce marché.`

En d'autres termes, comme l'offre freepro est considérée comme une offre "petits professionnels", on doit avoir un RIO fixe, obtenable au 3179

**Comment by spencefoxtrot** [comment]
Pourquoi le tag mobile ?
C'est l'offre fixe qui pose problème initialement :)

**Comment by kgersen** [comment]
Je pensais que ca ne concernait que les lignes mobiles de l'offre (qui ont le même souci).
Du coup je rajoute un tag pour tout ce qui est téléphonie fixe et renomme le tag 'mobile'.
A ce jour il y a donc ce problème sur les 2 types de lignes.

**Comment by rmanus** [comment]
Le code RIO pour ligne fixe devrait être maintenant disponible dans l'espace client

**Comment by kgersen** [comment]
ok pour fixe.
reste lignes mobiles donc. (l'appel au 3179  indique toujours 'désolé un incident technique ...')

**Comment by m2i11** [comment]
Les RIO des lignes mobiles sont aussi disponibles dans l'espace client
