### ISSUE TITLE
Messagerie via internet fonctionne pas

### ISSUE THREAD

**Issue by techview67** [LaFibre-info/Freepro#26]
Impossible de joindre https://mevo.freepro.com/
afin de pouvoir accéder à la messagerie

**Comment by rmanus** [comment]
L'accès à messagerie ne peut se faire que depuis une connexion à la Freebox Pro en local ou via VPN depuis l'espace client et la consultation des messages vocaux au 666

**Comment by techview67** [comment]
> 
> 
> L'accès à messagerie ne peut se faire que depuis une connexion à la Freebox Pro en local ou via VPN depuis l'espace client et la consultation des messages vocaux au 666

Quand j’appelle depuis la ligne branché à la freebox pro ( 666 ) ça me demande d'entrer un code d'accès que je n'ai jamais reçu.
Et le site : https://mevo.freepro.com ne fonctionne pas même sur un pc branché sur le réseau

**Comment by rmanus** [comment]
Je te conseille d'ouvrir un ticket au support FreePro
