### ISSUE TITLE
NAS : Impossible de créer un dossier ou un fichier portant le nom "ICONS"

### ISSUE THREAD

**Issue by YvesZAJ** [LaFibre-info/Freepro#33]
Il est impossible de créer sur le NAS un dossier ou un fichier portant le nom "Icons". Il est également impossible de renommer un dossier ou un fichier vers ce nom qui semble être un nom réservé.

Le bug a été confirmé par le support de FreePro, et devrait être corrigé à l'occasion du  déploiement du nouveau firmware du NAS.

![Impossible de creer un dossier de nom ICONS](https://user-images.githubusercontent.com/85571423/121213060-34129680-c87e-11eb-87d9-23a7fd12b8c5.png)

**Comment by rmanus** [comment]
Mise à jour du fix déployé en production
