### ISSUE TITLE
Graphiques de débits erronés

### ISSUE THREAD

**Issue by jps-gdd** [LaFibre-info/Freepro#34]
Etant en train de tester comme on peut la ligne freepro, on s'est aperçu que les graphes de la page d'accueil disent n'importe quoi.
Décalés de 2h sur l'heure France déjà (sur le GMT 0) et unité de mesure fausse:

![image](https://user-images.githubusercontent.com/72876185/121668333-7c62cc00-caab-11eb-9731-1b6e0be72968.png)

Des tests ce matin nous donnait environ 60Mo/s en upload.
Cependant, en allant sur le graph à la bonne période, on obtenait 6Gb/s de débit en upload consommé ... au lieu d'un peu plus de 600Mb/s

On peut aussi voir un débit affiché il y a quelques jours à 40Gb/s, j'imagine du 4Gb/s plutôt, quand on testait des PC branchés sur la partie switch et un sur la le SFP+ 10Gb

**Comment by PofMagicfingers** [comment]
(ce ticket duplique ou complète #17)

**Comment by jps-gdd** [comment]
Effectivement, je cloture
