### ISSUE TITLE
 Freebox PRO isolées entre elles

### ISSUE THREAD

**Issue by Fabliv** [LaFibre-info/Freepro#35]
Bonjour à tous,

Je viens de souscrire plusieurs ligne Free PRO pour plusieurs clients.

**Je viens de m'apercevoir d'un bug ENORME !**

L'un de mes clients à 2 sites (siège et succursale). Chaque site est connecté via une Freebox PRO en connexion principale et gérer par une passerelle (en DMZ sur la config firewall des Freebox) et qui me permet de faire du failover avec un ISP différent.
Le siège est évidemment le cœur du SI, hébergeant des services Web et un serveur RDS.

Les employés sont dans l'incapacité de joindre les services Web, ni de se connecter en VPN (serveur Interne) depuis la succursale lorsque les deux connexions Free PRO sont actives.
Après quelques tests, je me suis aperçu que les Freebox Pro sont dans l'incapacité de communiquer ensemble, elles sont comme isolées.
Pour précision, chacune des Freebox Pro a une adresse IPV4 publique sur le même pool d'adresse chez JAGUAR NETWORK.

De chez moi ou tout autre lieu avec une connexion Internet hors Free PRO, tout fonctionne.
Depuis d'autres Freebox PRO, les connexions sont impossibles.

J'ai eu un tech **JAGUAR NETWORK** d'astreinte ce soir, qui a eu la gentillesse de me répondre malgré le fait que je ne sois pas client direct et après mes explications, il a testé depuis un serveur derrière une Freebox Pro et depuis une autre connexion, il a obtenu le même résultat.
**Apparemment les Freebox PRO auraient un problème d'isolation de couche 3.**
Le tech n'en revenait pas et va informer les services idoines chez eux et Iliad, en espérant qu'ils interviennent au plus vite.

Heureusement, j'ai des connexions de backup en failover (fibre et ADSL), j'ai donc désactivé mes ports WAN sur Free PRO pour que mes backups prennent le relais et maintiennent les services. Sans ces backups, ce serait le chômage technique ou le télétravail forcé et impossible pour certains postes.  :-[

Merci de m'avoir lu.  ;)

Fabrice

**Comment by Patrick93110** [comment]
Bonsoir

J'avais déjà rencontré le même problème entre 2 Freebox "grand public" qui étaient dans le même pool d'adresses IP. 

J'avais dû modifier le routage pour forcer de passer par un autre ISP de secours pour joindre la Freebox de l'autre site.

**Comment by Fabliv** [comment]
Bonsoir Patrick,

Le tech JAGUAR NETWORK n'était pas sur le même pool lors de son test, d'après lui.
Je voudrai éviter d'avoir à faire du DNAT même temporaire sur mes passerelles pour palier à un bug ou une mauvaise configuration qui ne m'est pas propre. 

N'oublions pas que nous sommes sur une offre pro tout de même. ;)

**Comment by Oliviercreativ** [comment]
Ah tiens de mon coté je n'ai plus de VPN ! 
Il me semblerait quand j'ai activé le firewall, le VPN est tombé ...

**Comment by kgersen** [comment]
en IPv6 aussi ?

**Comment by Oliviercreativ** [comment]
non IPV4

**Comment by mgerini** [comment]
> Depuis d'autres Freebox PRO, les connexions sont impossibles.
Un correctif vient d'être appliqué pour résoudre le problème sur IPv4

**Comment by Oliviercreativ** [comment]
Ah yes merci je vais la reboot ;)

**Comment by Oliviercreativ** [comment]
Quand j'essaye de me connecter, il me dit sur le 192.0.0.8, alors qu'il m'a semblé voir qui se connecter sur 192.168.2.1.
Je vais tel au SAV ;)

**Comment by Fabliv** [comment]
Bonjour, @mgerini un reboot de la Freebox est obligatoire ?

**Comment by mgerini** [comment]
> Bonjour, @mgerini un reboot de la Freebox est obligatoire ?


Bonjour @Fabliv , pas de reboot nécessaire pour le problème de communication entre 2 Freebox

**Comment by Fabliv** [comment]
@mgerini, il me semblait bien. Je ferai mes tests ce soir. Mes Freebox Pro sont sur le même /22.

Merci de votre prompt réactivité.

**Comment by Fabliv** [comment]
@mgerini, @kgersen, je viens de réactiver mon lien Free Pro au siège, les deux Freebox arrivent à dialoguer.
Merci pour le correctif rapide.

(Issue Solved) ;)
