### ISSUE TITLE
Redemarrer la Freebox Pro a distance

### ISSUE THREAD

**Issue by dtipir** [LaFibre-info/Freepro#39]
Bonjour,

Si j'ai bien fait attention, actuellement il n'est pas possible de redemarrer la box a distance depuis l'espace client.
Pouvez-vous ajouter la fonctionnalité ?

**Comment by kgersen** [comment]
c'est implémenté. (dans  "autodiag" )

**Comment by kgersen** [comment]
fausse joie.la modif a été annulé pour le moment en tout cas.

**Comment by kgersen** [comment]
ca fonctionne.
