### ISSUE TITLE
Pas de VoLTE

### ISSUE THREAD

**Issue by matnoublanche** [LaFibre-info/Freepro#46]
Tout comme le VoWiFi sur l'issue #41, on n'a toujours pas d'option VoLTE sur la téléphonie.

**Comment by matnoublanche** [comment]
Suite aux annonce de Free, avons-nous des nouvelles en ce qui concerne Free Pro pour la VoWiFi et la VoLTE ?

**Comment by kgersen** [comment]
Jusqu'ici il n'y a pas de communication chez FreePro , quelque soit le sujet d'ailleurs.

Pour volte, le site https://mobile.free.fr/VoLTE.html indique clairement pas freepro pour le moment.

**Comment by matnoublanche** [comment]
J'étais passé à côté de l'info, mais c'est maintenant actif !

https://www.universfreebox.com/article/509621/free-pro-lance-la-volte-pour-tous-ses-abonnes
