### ISSUE TITLE
Impossible d'attribuer l'ip privé 192.168.1.100

### ISSUE THREAD

**Issue by dtipir** [LaFibre-info/Freepro#52]
Bonjour,

Depuis qu'on peut modifier les adresses IP privé, je n'arrive pas a attribuer automatiquement via DHCP de la Freebox Pro l'ip 192.168.1.100

Sous-reseau: 192.168.1.0
Passerelle: 192.168.1.1
Masque de sous-réseau : 255.255.255.0/24
Debut DHCP: 192.168.1.2
Fin DHCP: 192.168.1.100

(192.168.1.101 pour la fin du DHCP cela ne change rien !)

Si je met comme baux statique: 

192.168.1.100 --> ne fonctionne pas, meme apres plusieurs redemarrage du peripherique (box, switch etc..)
192.168.1.5 --> fonctionne parfaitement

**Comment by rmanus** [comment]
On vient de faire le test avec une config identique et ça fonctionne...

**Comment by HectordeMars** [comment]
Bonjour, 
Oui c'est une restriction connue, je ne sais pas encore trop pourquoi qq'un a imposé cette limite.
192.168.0.0/24 ok
192.168.0.0/23 nok
Peut être que ça vient de JN (Jaguar Network) qui économise les DHCP et travaille sur le reverse et qu'à terme il n'est pas impossible que FreePro propose un service d'hébergement de site web.
à suivre

**Comment by kgersen** [comment]
pas de retour de l'OP. je cloture.
