### ISSUE TITLE
NAS chez FreePro et ONU :)

### ISSUE THREAD

**Issue by HectordeMars** [LaFibre-info/Freepro#57]
Optimisation de la Box et gain de place (surchauffe ? techniquement possible ?)
1 / Le NAS de la FreePro se résume à deux HDD ou SSD d'1To chacun en Raid1, pourquoi  encore des disques durs alors qu'il existe des cartes mémoire qui pourraient faire le même boulot ? (=gain de place)
2 / L'ONU de la FreePro, pourquoi n'est il pas intégré à la box et ainsi éviter bon nombre de souci de livraison, de panne , d'installation, de branchement etc

**Comment by kgersen** [comment]
ceci est un "bug tracker", pas un forum.
Limitez chaque 'issue" a un sujet / problème bien précis et pas a de vagues suggestions groupées.

Il y a un forum non officiel ici: https://lafibre.info/free-pro/
