### ISSUE TITLE
Email @pro.free.fr

### ISSUE THREAD

**Issue by HectordeMars** [LaFibre-info/Freepro#61]
Bonjour,
Pour l'instant pas d'adresse mail en @pro.free.fr pour les nouveaux clients

**Comment by kgersen** [comment]
Je vois pas pourquoi un pro voudrait un email terminant par @pro.free.fr ...

Je laisse temporairement ouvert si d'autres personnes +1 cette demande.

**Comment by HectordeMars** [comment]
Je viens d'apprendre que le reverse DNS ne correspondait pas au DNS primaire > 

**mafreebox.freepro.com** --> 212.27.38.253
mais le reverse:
212.27.38.253 --> **freeplayer.freebox.fr**.
