### ISSUE TITLE
Mode bridge

### ISSUE THREAD

**Issue by HectordeMars** [LaFibre-info/Freepro#62]
quelles sont les entreprises qui demandent le mode bridge ? les énormes entreprises.
pourquoi demandent t elles ce mode de fonctionnement d'une box ? car elles veulent un nœud supplémentaire.
pourquoi veulent elles un nœud supplémentaire ? car derrière il y a une énorme infrastructure réseau câblé.

il s'agit d'une évolution firmware prioritaire au regard des objectifs de l'offre, ce n'est pas un bug à proprement parlé

**Comment by kgersen** [comment]
redondant avec #6
