### ISSUE TITLE
Ipv6 hack de l'interface

### ISSUE THREAD

**Issue by HectordeMars** [LaFibre-info/Freepro#65]
Bonjour,

J'ai bien essayé de changer le code html de l'espace client rubrique, "Mes Freebox Pro", puis "Ma Freebox Pro", puis l'onglet "Firewall" > Wan/LAN > créer une règle > "Activer le redirection de port", tout ceci en Ipv4.

A cette adresse > https://support-pro.free.fr/comment-gerer-la-redirection-de-ports-dnat/ , sur le site de Freepro il y a une config en Ipv4 mais pas en Ipv6 car le bouton "Ip de redirection", dans l'onglet Ipv6 est grisé.

**Comment by kgersen** [comment]
on ne fait pas ce genre de chose en IPv6.
redondant avec  #31
