### ISSUE TITLE
Intégration des infrastructures / Interconnexions multisites

### ISSUE THREAD

**Issue by HectordeMars** [LaFibre-info/Freepro#66]
Bonjour, 

Il me semblait important d'intervenir à ce sujet en terme d'évolution et d'amélioration souhaitée.

SD-WAN ?

**Comment by kgersen** [comment]
trop vague et trop de sujets. C'est un bug tracker ici.

**Comment by HectordeMars** [comment]
oui c'est vrai à proprement parlé ce n'est pas un bug de la box. 

Mais si vous voulez raisonner en terme de bug, le plus gros bug que j'ai rencontré jusqu'à maintenant sur la Freebox Pro c'est sa difficulté à mettre en place les maj firmware (sic). 

La plupart du temps elle reste bloquée sur une étape 3 ou 4 avec le message qui va bien : " ...erreur de téléchargement du firmware.." ...un truc du genre.

Un redémarrage de la box 48 h après sa mise en service en général suffit à régler le problème, mais ce n'est pas aussi catégorique, parfois elle n'y arrive pas et à ce moment là il faut intervenir en amont (ex : recharger la collecte)

En ce qui concerne de SD-Wan ce n'est pas un bug certes, sauf que lorsqu'on s'adresse à des pros en terme d'offre il faut parer à 'toutes' les éventualités et pour autant que je sache c'est un truc qui est logique.

La plupart du temps les grosses boites (entreprises) ont un siège et des succursales, parfois éparpillés à travers le globe...à mon sens il serait opportun de leurs permettre de pouvoir gérer l'ensemble de leur site au travers d'une seule et unique interface.

Je dis ça je dis rien
