### ISSUE TITLE
Reverse DNS non configuré et non configurable

### ISSUE THREAD

**Issue by konandrum** [LaFibre-info/Freepro#81]
Le reverse DNS n'est pas configurable ce qui rend très compliqué d’héberger son propre serveur de mail à cause des règles anti spam sur les serveur d'email moderne.

Depuis quelques semaine la configuration rDNS à sauté sans explications, il n'y a même plus d'entrée rDNS associé à l'adresse ip dédiée de la box !

**Comment by kgersen** [comment]
doublon #8
